// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxjzRJxP7fupVRuVTVaWOrt7LlLy9X-c',
    appId: '1:1040824737850:web:d214e3597c64eb3cb39503',
    messagingSenderId: '1040824737850',
    projectId: 'nevinschatapp',
    authDomain: 'nevinschatapp.firebaseapp.com',
    storageBucket: 'nevinschatapp.appspot.com',
    measurementId: 'G-KBDT4CV7ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-11KSqCMguNBc3uhCsUO38NNBC-zbyaE',
    appId: '1:1040824737850:android:4a1654d1eafa1de8b39503',
    messagingSenderId: '1040824737850',
    projectId: 'nevinschatapp',
    storageBucket: 'nevinschatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgMezOHdHSy-5EtuUHWOWy5TxdrgNnSM',
    appId: '1:1040824737850:ios:f43737ca48080f1bb39503',
    messagingSenderId: '1040824737850',
    projectId: 'nevinschatapp',
    storageBucket: 'nevinschatapp.appspot.com',
    androidClientId: '1040824737850-7o2s1nn15hgniebagr4sqa15jinkth17.apps.googleusercontent.com',
    iosClientId: '1040824737850-ajs4m9drd71mc6t6vledg3qf1els8tac.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgMezOHdHSy-5EtuUHWOWy5TxdrgNnSM',
    appId: '1:1040824737850:ios:e9126a523dd67e91b39503',
    messagingSenderId: '1040824737850',
    projectId: 'nevinschatapp',
    storageBucket: 'nevinschatapp.appspot.com',
    androidClientId: '1040824737850-7o2s1nn15hgniebagr4sqa15jinkth17.apps.googleusercontent.com',
    iosClientId: '1040824737850-ah34kk26467dku2q2ocdp1mb7qtp6lru.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
